CREATE OR REPLACE VIEW NPSS_VW_CUST_ACCT_NO AS
SELECT CUSTOMER, ACCOUNT_NO
  FROM (SELECT A.CUSTOMER, A.NPSSCPA_ID, B.ACCOUNT_NO,A.TENANT_ID
          FROM NPSS_CUST_PROXY_ADDRESS A
         INNER JOIN NPSS_CUST_PROXY_BANKS B ON A.NPSSCPA_ID = B.NPSSCPA_ID) V