DROP VIEW IF EXISTS NPSS_VW_DST_RTN_MAP;
@SPL@
CREATE OR REPLACE VIEW  NPSS_VW_DST_RTN_MAP AS
SELECT CONCAT(RETURN_CODE,'~',RETURN_DESCRIPTION)DST_CODE_DESC,
	RETURN_CODE,
	PROCESSING_SYSTEM,
	TENANT_ID,
	NEED_SYNC
FROM CORE_NC_RETURN_CODES