drop view if exists CORE_VW_VALIDATION_CODE;
CREATE OR REPLACE VIEW  CORE_VW_VALIDATION_CODE AS
SELECT  V_CODE,V_DESC,
CONCAT(CONCAT(V_CODE, ' - '), V_DESC) AS DESCRIPTION,STATUS,TENANT_ID,V_TYPE FROM CORE_NC_VALIDATIONS